import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { spawnSync } from 'node:child_process'
import { fileURLToPath } from 'node:url'

import {
  materializeExamples,
  repoRoot,
} from './verify-m049-s03-materialize-examples.mjs'

const scriptDir = path.dirname(fileURLToPath(import.meta.url))
const scriptPath = path.join(scriptDir, 'verify-m049-s03-materialize-examples.mjs')

function mkTmpDir(t, prefix) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), prefix))
  t.after(() => fs.rmSync(dir, { recursive: true, force: true }))
  return dir
}

function writeFiles(rootDir, files) {
  for (const [relativePath, content] of Object.entries(files)) {
    const absolutePath = path.join(rootDir, relativePath)
    fs.mkdirSync(path.dirname(absolutePath), { recursive: true })
    fs.writeFileSync(absolutePath, content)
  }
}

function sqliteFixtureFiles() {
  return {
    'mesh.toml': '[package]\nname = "todo-sqlite"\nversion = "0.1.0"\n',
    'main.mpl': 'fn main() do\n  println("sqlite")\nend\n',
    'config.mpl': 'pub fn mode() -> String do\n  "sqlite"\nend\n',
    'README.md': '# todo-sqlite\n\nThis project was generated by `meshc init --template todo-api --db sqlite`.\n',
    'Dockerfile': 'FROM ubuntu:24.04\n',
    '.dockerignore': '*.sqlite3\n',
    'api/health.mpl': 'pub fn handle_health(_request) do\n  HTTP.response(200, json { status : "ok" })\nend\n',
    'api/router.mpl': 'pub fn build_router() do\n  HTTP.router()\nend\n',
    'api/todos.mpl': 'pub fn handle_list_todos(_request) do\n  HTTP.response(200, "[]")\nend\n',
    'runtime/registry.mpl': 'pub fn get_db_path() -> String do\n  "todo.sqlite3"\nend\n',
    'services/rate_limiter.mpl': 'pub fn allow_write(_pid, _key :: String) -> Bool do\n  true\nend\n',
    'storage/todos.mpl': 'pub fn ensure_schema(_db_path :: String) -> Int ! String do\n  Ok(0)\nend\n',
    'types/todo.mpl': 'pub struct Todo do\n  id :: String\nend deriving(Json, Row)\n',
    'tests/config.test.mpl': 'test("sqlite config") do\n  assert(true)\nend\n',
    'tests/storage.test.mpl': 'test("sqlite storage") do\n  assert(true)\nend\n',
  }
}

function postgresFixtureFiles() {
  return {
    'mesh.toml': '[package]\nname = "todo-postgres"\nversion = "0.1.0"\n',
    'main.mpl': 'fn main() do\n  println("postgres")\nend\n',
    'work.mpl': '@cluster pub fn sync_todos() -> Int do\n  1 + 1\nend\n',
    'config.mpl': 'pub fn mode() -> String do\n  "postgres"\nend\n',
    'README.md': '# todo-postgres\n\nThis project was generated by `meshc init --template todo-api --db postgres`.\n',
    'Dockerfile': 'FROM ubuntu:24.04\n',
    '.dockerignore': '.env\n',
    '.env.example': 'DATABASE_URL=postgres://postgres:postgres@127.0.0.1:5432/todo-postgres\n',
    'api/health.mpl': 'pub fn handle_health(_request) do\n  HTTP.response(200, json { status : "ok" })\nend\n',
    'api/router.mpl': 'pub fn build_router() do\n  HTTP.router()\nend\n',
    'api/todos.mpl': 'pub fn handle_list_todos(_request) do\n  HTTP.response(200, "[]")\nend\n',
    'runtime/registry.mpl': 'pub fn get_pool() do\n  nil\nend\n',
    'services/rate_limiter.mpl': 'pub fn allow_write(_pid, _key :: String) -> Bool do\n  true\nend\n',
    'storage/todos.mpl': 'pub fn list_todos(_pool :: PoolHandle) -> String ! String do\n  Ok("[]")\nend\n',
    'types/todo.mpl': 'pub struct Todo do\n  id :: String\nend deriving(Json)\n',
    'tests/config.test.mpl': 'test("postgres config") do\n  assert(true)\nend\n',
    'migrations/20260402120000_create_todos.mpl': 'pub fn up(_pool :: PoolHandle) -> Int ! String do\n  Ok(0)\nend\n',
  }
}

function createFakeMeshc(t, { failDb = '' } = {}) {
  const tempDir = mkTmpDir(t, 'm049-s03-fake-meshc-')
  const fixturesRoot = path.join(tempDir, 'fixtures')
  writeFiles(path.join(fixturesRoot, 'sqlite'), sqliteFixtureFiles())
  writeFiles(path.join(fixturesRoot, 'postgres'), postgresFixtureFiles())

  const meshcBin = path.join(tempDir, 'fake-meshc.mjs')
  const source = `#!/usr/bin/env node
import fs from 'node:fs'
import path from 'node:path'

const fixtureRoot = ${JSON.stringify(fixturesRoot)}
const failDb = ${JSON.stringify(failDb)}
const args = process.argv.slice(2)
if (args.length !== 6 || args[0] !== 'init' || args[1] !== '--template' || args[2] !== 'todo-api' || args[3] !== '--db') {
  process.stderr.write(\`unexpected args: \${args.join(' ')}\\n\`)
  process.exit(64)
}
const db = args[4]
const name = args[5]
if (db === failDb) {
  process.stdout.write(\`stdout failure for \${db}\\n\`)
  process.stderr.write(\`stderr failure for \${db}\\n\`)
  process.exit(23)
}
const fixtureDir = path.join(fixtureRoot, db)
if (!fs.existsSync(fixtureDir)) {
  process.stderr.write(\`missing fixture: \${fixtureDir}\\n\`)
  process.exit(91)
}
const projectDir = path.join(process.cwd(), name)
fs.cpSync(fixtureDir, projectDir, { recursive: true, force: false, errorOnExist: true })
process.stdout.write(\`created \${name} from \${db}\\n\`)
`
  fs.writeFileSync(meshcBin, source)
  fs.chmodSync(meshcBin, 0o755)
  return meshcBin
}

function runCli(args, options = {}) {
  return spawnSync(process.execPath, [scriptPath, ...args], {
    cwd: repoRoot,
    encoding: 'utf8',
    ...options,
  })
}

test('materializeExamples writes temp example trees, preserves sqlite/postgres differences, and check mode passes', (t) => {
  const meshcBin = createFakeMeshc(t)
  const tempDir = mkTmpDir(t, 'm049-s03-materialize-')
  const examplesRoot = path.join(tempDir, 'examples')

  const firstWrite = materializeExamples({
    mode: 'write',
    meshcBin,
    examplesRoot,
    tempParent: tempDir,
  })

  assert.equal(firstWrite.examples.length, 2)
  assert.ok(fs.existsSync(path.join(examplesRoot, 'todo-sqlite', 'tests/storage.test.mpl')))
  assert.ok(!fs.existsSync(path.join(examplesRoot, 'todo-sqlite', 'work.mpl')))
  assert.ok(fs.existsSync(path.join(examplesRoot, 'todo-postgres', 'work.mpl')))
  assert.ok(fs.existsSync(path.join(examplesRoot, 'todo-postgres', '.env.example')))
  assert.match(
    fs.readFileSync(path.join(examplesRoot, 'todo-sqlite', 'README.md'), 'utf8'),
    /meshc init --template todo-api --db sqlite/,
  )

  fs.writeFileSync(path.join(examplesRoot, 'todo-sqlite', 'README.md'), '# stale\n')
  fs.writeFileSync(path.join(examplesRoot, 'todo-sqlite', 'notes.txt'), 'remove me\n')

  const secondWrite = materializeExamples({
    mode: 'write',
    meshcBin,
    examplesRoot,
    tempParent: tempDir,
  })

  const sqliteReadme = fs.readFileSync(path.join(examplesRoot, 'todo-sqlite', 'README.md'), 'utf8')
  assert.match(sqliteReadme, /meshc init --template todo-api --db sqlite/)
  assert.ok(!fs.existsSync(path.join(examplesRoot, 'todo-sqlite', 'notes.txt')))
  assert.ok(secondWrite.lines.some((line) => line.includes('phase=write example=todo-sqlite')))

  const check = materializeExamples({
    mode: 'check',
    meshcBin,
    examplesRoot,
    tempParent: tempDir,
  })
  assert.ok(check.lines.some((line) => line.includes('phase=check example=todo-sqlite')))
  assert.ok(check.lines.some((line) => line.includes('phase=check example=todo-postgres')))
})

test('materializeExamples check mode names missing, extra, and changed files', (t) => {
  const meshcBin = createFakeMeshc(t)
  const tempDir = mkTmpDir(t, 'm049-s03-diff-')
  const examplesRoot = path.join(tempDir, 'examples')

  materializeExamples({
    mode: 'write',
    meshcBin,
    examplesRoot,
    tempParent: tempDir,
  })

  fs.rmSync(path.join(examplesRoot, 'todo-sqlite', 'tests/storage.test.mpl'))
  fs.writeFileSync(path.join(examplesRoot, 'todo-sqlite', 'README.md'), '# drift\n')
  fs.writeFileSync(path.join(examplesRoot, 'todo-sqlite', 'notes.txt'), 'extra\n')

  let failure = null
  try {
    materializeExamples({
      mode: 'check',
      meshcBin,
      examplesRoot,
      tempParent: tempDir,
    })
  } catch (error) {
    failure = error
  }

  assert.ok(failure instanceof Error, 'expected drift check to fail')
  assert.match(failure.message, /example=todo-sqlite/)
  assert.match(failure.message, /missing=tests\/storage\.test\.mpl/)
  assert.match(failure.message, /extra=notes\.txt/)
  assert.match(failure.message, /changed=README\.md/)
})

test('materializeExamples rejects unsafe examples roots and malformed partial targets before writing', (t) => {
  const meshcBin = createFakeMeshc(t)
  const tempDir = mkTmpDir(t, 'm049-s03-guards-')

  assert.throws(
    () => materializeExamples({
      mode: 'write',
      meshcBin,
      examplesRoot: path.join(tempDir, 'not-examples'),
      tempParent: tempDir,
    }),
    /examples root must end with \/examples/,
  )

  const examplesRoot = path.join(tempDir, 'examples')
  fs.mkdirSync(path.join(examplesRoot, 'todo-sqlite'), { recursive: true })
  fs.writeFileSync(path.join(examplesRoot, 'todo-sqlite', 'README.md'), '# partial\n')

  let failure = null
  try {
    materializeExamples({
      mode: 'write',
      meshcBin,
      examplesRoot,
      tempParent: tempDir,
    })
  } catch (error) {
    failure = error
  }

  assert.ok(failure instanceof Error, 'expected partial target validation to fail')
  assert.match(failure.message, /target .*todo-sqlite.*missing required files:/)
  assert.equal(fs.readFileSync(path.join(examplesRoot, 'todo-sqlite', 'README.md'), 'utf8'), '# partial\n')
})

test('materializeExamples surfaces generation stdout and stderr and does not write partial targets', (t) => {
  const meshcBin = createFakeMeshc(t, { failDb: 'sqlite' })
  const tempDir = mkTmpDir(t, 'm049-s03-failure-')
  const examplesRoot = path.join(tempDir, 'examples')

  let failure = null
  try {
    materializeExamples({
      mode: 'write',
      meshcBin,
      examplesRoot,
      tempParent: tempDir,
    })
  } catch (error) {
    failure = error
  }

  assert.ok(failure instanceof Error, 'expected generation failure to throw')
  assert.match(failure.message, /stdout failure for sqlite/)
  assert.match(failure.message, /stderr failure for sqlite/)
  assert.ok(!fs.existsSync(path.join(examplesRoot, 'todo-sqlite')))
  assert.ok(!fs.existsSync(path.join(examplesRoot, 'todo-postgres')))
})

test('CLI rejects unknown arguments and invalid MESHC_BIN or --meshc-bin overrides', (t) => {
  const tempDir = mkTmpDir(t, 'm049-s03-cli-')
  const examplesRoot = path.join(tempDir, 'examples')
  const missingMeshc = path.join(tempDir, 'missing-meshc')

  const unknownArg = runCli(['--bogus'], {})
  assert.equal(unknownArg.status, 1)
  assert.match(unknownArg.stderr, /unknown argument: --bogus/)

  const invalidEnv = runCli(['--check', '--examples-root', examplesRoot], {
    env: {
      ...process.env,
      MESHC_BIN: missingMeshc,
    },
  })
  assert.equal(invalidEnv.status, 1)
  assert.match(invalidEnv.stderr, /MESHC_BIN does not exist/)

  const invalidFlag = runCli(['--check', '--examples-root', examplesRoot, '--meshc-bin', missingMeshc])
  assert.equal(invalidFlag.status, 1)
  assert.match(invalidFlag.stderr, /--meshc-bin does not exist/)
})
