//! Project scaffolding for `meshc init`.
//!
//! Creates one of three standard Mesh project layouts:
//!
//! ```text
//! <name>/
//!   mesh.toml
//!   main.mpl
//! ```
//!
//! or, for `meshc init --clustered`:
//!
//! ```text
//! <name>/
//!   mesh.toml
//!   main.mpl
//!   work.mpl
//!   README.md
//! ```
//!
//! or, for `meshc init --template todo-api`:
//!
//! ```text
//! <name>/
//!   mesh.toml
//!   main.mpl
//!   work.mpl
//!   README.md
//!   Dockerfile
//!   .dockerignore
//!   api/
//!   runtime/
//!   services/
//!   storage/
//!   types/
//! ```

use std::path::{Path, PathBuf};

fn create_project_dir(name: &str, dir: &Path) -> Result<PathBuf, String> {
    let project_dir = dir.join(name);

    if project_dir.exists() {
        return Err(format!("Directory '{}' already exists", name));
    }

    std::fs::create_dir_all(&project_dir)
        .map_err(|e| format!("Failed to create directory '{}': {}", name, e))?;
    Ok(project_dir)
}

fn write_project_file(path: &Path, contents: &str) -> Result<(), String> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .map_err(|e| format!("Failed to create directory '{}': {}", parent.display(), e))?;
    }
    std::fs::write(path, contents).map_err(|e| format!("Failed to write {}: {}", path.display(), e))
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TodoApiDatabase {
    Sqlite,
    Postgres,
}

/// Create a new hello-world Mesh project with the given name inside the given parent directory.
pub fn scaffold_project(name: &str, dir: &Path) -> Result<(), String> {
    let project_dir = create_project_dir(name, dir)?;

    let manifest = format!(
        r#"[package]
name = "{}"
version = "0.1.0"

[dependencies]
"#,
        name
    );
    write_project_file(&project_dir.join("mesh.toml"), &manifest)?;

    let main_mesh = r#"fn main() do
  IO.puts("Hello from Mesh!")
end
"#;
    write_project_file(&project_dir.join("main.mpl"), main_mesh)?;

    println!("Created project '{}'", name);
    Ok(())
}

/// Create a new clustered Mesh project that uses only the public clustered-app contract.
pub fn scaffold_clustered_project(name: &str, dir: &Path) -> Result<(), String> {
    let project_dir = create_project_dir(name, dir)?;

    let manifest = format!(
        r#"[package]
name = "{}"
version = "0.1.0"

[dependencies]
"#,
        name
    );
    write_project_file(&project_dir.join("mesh.toml"), &manifest)?;

    let main_mesh = r#"fn log_bootstrap(status :: BootstrapStatus) do
  println(
    "[clustered-app] runtime bootstrap mode=#{status.mode} node=#{status.node_name} cluster_port=#{status.cluster_port} discovery_seed=#{status.discovery_seed}"
  )
end

fn log_bootstrap_failure(reason :: String) do
  println("[clustered-app] runtime bootstrap failed reason=#{reason}")
end

fn main() do
  case Node.start_from_env() do
    Ok(status) -> log_bootstrap(status)
    Err(reason) -> log_bootstrap_failure(reason)
  end
end
"#;
    write_project_file(&project_dir.join("main.mpl"), main_mesh)?;

    let work_mesh = r#"@cluster pub fn add() -> Int do
  1 + 1
end
"#;
    write_project_file(&project_dir.join("work.mpl"), work_mesh)?;

    let readme = format!(
        r#"# {name}

This project was generated by `meshc init --clustered`.

The generated files follow the same route-free clustered-work contract as `tiny-cluster/` and `cluster-proof/`: `mesh.toml` stays package-only, `work.mpl` declares the clustered work in source with `@cluster`, and `main.mpl` only boots through `Node.start_from_env()` while the runtime owns startup, placement, continuity, and diagnostics.

## Package contract

- `mesh.toml` is package-only and intentionally omits `[cluster]`
- `main.mpl` has one bootstrap path: `Node.start_from_env()`
- `work.mpl` defines `@cluster pub fn add()`
- the runtime-owned handler name is derived from the ordinary source function name as `Work.add`
- the visible work body stays `1 + 1`
- the project does not own HTTP routes, submit handlers, or work-delay seams

## Runtime contract

Set these environment variables when you want the app to participate in a cluster:

- `MESH_CLUSTER_COOKIE` — shared cluster cookie used for authenticated node traffic
- `MESH_NODE_NAME` — optional advertised node identity (`name@host:port`); defaults to `app@127.0.0.1:$MESH_CLUSTER_PORT`
- `MESH_DISCOVERY_SEED` — discovery seed used by the runtime DNS discovery loop
- `MESH_CLUSTER_PORT` — node listener port (default `4370`)
- `MESH_CONTINUITY_ROLE` — runtime continuity role (`primary` or `standby`)
- `MESH_CONTINUITY_PROMOTION_EPOCH` — bounded promotion epoch (`0` by default)

The runtime automatically starts the source-declared `@cluster` function and closes the continuity record when it returns.

## Runtime inspection

Once a built node is running in cluster mode, inspect it through Mesh-owned CLI surfaces instead of app-owned routes:

```bash
meshc cluster status <node-name@host:port> --json
meshc cluster continuity <node-name@host:port> --json
meshc cluster continuity <node-name@host:port> <request-key> --json
meshc cluster diagnostics <node-name@host:port> --json
```

Use the list form first to discover request keys and runtime-owned startup records, then inspect a single record when you want the per-request continuity detail.

## Local run example

```bash
meshc build .
MESH_CLUSTER_COOKIE=dev-cookie \
MESH_NODE_NAME=app@127.0.0.1:4370 \
MESH_DISCOVERY_SEED=localhost \
MESH_CLUSTER_PORT=4370 \
MESH_CONTINUITY_ROLE=primary \
MESH_CONTINUITY_PROMOTION_EPOCH=0 \
./{name}
```
"#,
        name = name
    );
    write_project_file(&project_dir.join("README.md"), &readme)?;

    println!("Created clustered project '{}'", name);
    Ok(())
}

fn todo_readme(name: &str) -> String {
    r#"# __NAME__

This project was generated by `meshc init --template todo-api`.

It keeps the clustered-function contract source-first and route-free while giving you a real HTTP starter: a SQLite-backed Todo API, a process-backed write rate limiter, and a Dockerfile that packages the binary produced by `meshc build .` instead of assuming access to the Mesh repo.

## Project layout

```text
__NAME__/
  mesh.toml
  main.mpl
  work.mpl
  README.md
  Dockerfile
  .dockerignore
  api/
    health.mpl
    router.mpl
    todos.mpl
  runtime/
    registry.mpl
  services/
    rate_limiter.mpl
  storage/
    todos.mpl
  types/
    todo.mpl
```

## Clustered contract

- `mesh.toml` stays package-only and intentionally omits `[cluster]`
- `main.mpl` boots through `Node.start_from_env()` before starting the local HTTP server
- `work.mpl` declares `@cluster pub fn sync_todos()`
- the runtime-owned handler name is derived from the ordinary source function name as `Work.sync_todos`
- `GET /todos` and `GET /todos/:id` use `HTTP.clustered(1, ...)` so the starter truthfully dogfoods the shipped wrapper while `GET /health` and mutating routes stay local

## HTTP routes

- `GET /health` — local runtime + rate-limit configuration snapshot
- `GET /todos` — list todos through `HTTP.clustered(1, ...)`
- `GET /todos/:id` — fetch one todo through `HTTP.clustered(1, ...)`
- `POST /todos` — create from `{"title":"Buy milk"}`
- `PUT /todos/:id` — toggle completion
- `DELETE /todos/:id` — delete a todo

Mutating routes (`POST`, `PUT`, `DELETE`) stay local and go through the actor-backed limiter in `services/rate_limiter.mpl`.

## Environment

- `PORT` — HTTP port (`8080` by default)
- `TODO_DB_PATH` — SQLite database path (`todo.sqlite3` by default)
- `TODO_RATE_LIMIT_WINDOW_SECONDS` — limiter window length (`60` by default)
- `TODO_RATE_LIMIT_MAX_REQUESTS` — allowed mutating requests per window (`5` by default)
- `MESH_CLUSTER_COOKIE`, `MESH_NODE_NAME`, `MESH_DISCOVERY_SEED`, `MESH_CLUSTER_PORT`, `MESH_CONTINUITY_ROLE`, `MESH_CONTINUITY_PROMOTION_EPOCH` — optional clustered-runtime env when you want the runtime-owned operator flow

## Local run

```bash
meshc build .
PORT=8080 \
TODO_DB_PATH=./todo.sqlite3 \
TODO_RATE_LIMIT_WINDOW_SECONDS=60 \
TODO_RATE_LIMIT_MAX_REQUESTS=5 \
./__NAME__
```

## Runtime inspection

When you boot the app in clustered mode, inspect the runtime-owned state through Mesh CLI surfaces instead of package-owned control routes:

```bash
meshc cluster status <node-name@host:port> --json
meshc cluster continuity <node-name@host:port> --json
meshc cluster continuity <node-name@host:port> <request-key> --json
meshc cluster diagnostics <node-name@host:port> --json
```

Use the continuity list form first to discover runtime-owned startup records.

## Docker

Build the Linux binary you want to ship, then package that `./output` artifact into the image:

```bash
meshc build .
docker build -t __NAME__ .
```

Re-run `meshc build .` before rebuilding the image, and build on the Linux target you plan to run because the Dockerfile copies the already-compiled `./output` binary into the container. If you're driving Docker from macOS or Windows, emit `./output` from a Linux builder host, CI job, or container first.

Run it with a persisted SQLite volume:

```bash
docker run --rm \
  -p 8080:8080 \
  -e PORT=8080 \
  -e TODO_DB_PATH=/var/lib/todo/todo.sqlite3 \
  -v todo-data:/var/lib/todo \
  __NAME__
```
"#
    .replace("__NAME__", name)
}

fn todo_dockerfile(name: &str) -> String {
    r#"FROM ubuntu:24.04
RUN apt-get update \
  && apt-get install -y --no-install-recommends ca-certificates \
  && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY output /usr/local/bin/__NAME__
ENV PORT=8080
ENV TODO_DB_PATH=/var/lib/todo/todo.sqlite3
ENV TODO_RATE_LIMIT_WINDOW_SECONDS=60
ENV TODO_RATE_LIMIT_MAX_REQUESTS=5
ENV MESH_CLUSTER_PORT=4370
VOLUME ["/var/lib/todo"]
EXPOSE 8080 4370
ENTRYPOINT ["/usr/local/bin/__NAME__"]
"#
    .replace("__NAME__", name)
}

/// Create a new Todo API starter template using the default SQLite backend.
pub fn scaffold_todo_api_project(name: &str, dir: &Path) -> Result<(), String> {
    scaffold_todo_api_project_with_db(name, dir, TodoApiDatabase::Sqlite)
}

/// Create a new Todo API starter template for the selected database backend.
pub fn scaffold_todo_api_project_with_db(
    name: &str,
    dir: &Path,
    database: TodoApiDatabase,
) -> Result<(), String> {
    match database {
        TodoApiDatabase::Sqlite => scaffold_sqlite_todo_api_project(name, dir),
        TodoApiDatabase::Postgres => scaffold_postgres_todo_api_project(name, dir),
    }
}

fn scaffold_postgres_todo_api_project(_name: &str, _dir: &Path) -> Result<(), String> {
    Err("`meshc init --template todo-api --db postgres <name>` is reserved for the Postgres starter and is not implemented yet; use `meshc init --template todo-api <name>` or `--db sqlite` for the current SQLite starter.".to_string())
}

/// Create a new clustered SQLite Todo API starter template.
fn scaffold_sqlite_todo_api_project(name: &str, dir: &Path) -> Result<(), String> {
    let project_dir = create_project_dir(name, dir)?;

    let manifest = format!(
        r#"[package]
name = "{}"
version = "0.1.0"

[dependencies]
"#,
        name
    );
    write_project_file(&project_dir.join("mesh.toml"), &manifest)?;

    let main_mesh = r#"from Api.Router import build_router
from Runtime.Registry import start_registry
from Services.RateLimiter import start_rate_limiter
from Storage.Todos import ensure_schema

fn log_bootstrap(status :: BootstrapStatus) do
  println(
    "[todo-api] runtime bootstrap mode=#{status.mode} node=#{status.node_name} cluster_port=#{status.cluster_port} discovery_seed=#{status.discovery_seed}"
  )
end

fn log_bootstrap_failure(reason :: String) do
  println("[todo-api] runtime bootstrap failed reason=#{reason}")
end

fn env_positive_int(name :: String, default_value :: Int) -> Int do
  let raw = Env.get(name, "")
  if raw == "" do
    default_value
  else
    let value = Env.get_int(name, -1)
    if value > 0 do
      value
    else
      default_value
    end
  end
end

fn start_http_runtime(port :: Int, db_path :: String, window_seconds :: Int, max_requests :: Int) do
  let limiter_pid = start_rate_limiter(window_seconds, max_requests)
  start_registry(db_path, limiter_pid, window_seconds, max_requests)
  println(
    "[todo-api] Runtime ready port=#{port} db_path=#{db_path} write_limit_window_seconds=#{window_seconds} write_limit_max=#{max_requests}"
  )
  let router = build_router()
  HTTP.serve(router, port)
end

fn main() do
  case Node.start_from_env() do
    Ok(status) -> log_bootstrap(status)
    Err(reason) -> log_bootstrap_failure(reason)
  end

  let port = env_positive_int("PORT", 8080)
  let db_path = Env.get("TODO_DB_PATH", "todo.sqlite3")
  let window_seconds = env_positive_int("TODO_RATE_LIMIT_WINDOW_SECONDS", 60)
  let max_requests = env_positive_int("TODO_RATE_LIMIT_MAX_REQUESTS", 5)

  case ensure_schema(db_path) do
    Ok(_) -> start_http_runtime(port, db_path, window_seconds, max_requests)
    Err(reason) -> println("[todo-api] Database init failed: #{reason}")
  end
end
"#;
    write_project_file(&project_dir.join("main.mpl"), main_mesh)?;

    let work_mesh = r#"@cluster pub fn sync_todos() -> Int do
  1 + 1
end
"#;
    write_project_file(&project_dir.join("work.mpl"), work_mesh)?;

    let health_mesh = r#"from Runtime.Registry import get_db_path, get_max_requests, get_window_seconds

pub fn handle_health(_request) do
  HTTP.response(200,
  json {
    status : "ok",
    db_path : get_db_path(),
    clustered_handler : "Work.sync_todos",
    rate_limit_window_seconds : get_window_seconds(),
    rate_limit_max_requests : get_max_requests()
  })
end
"#;
    write_project_file(&project_dir.join("api/health.mpl"), health_mesh)?;

    let router_mesh = r#"from Api.Health import handle_health
from Api.Todos import handle_create_todo, handle_delete_todo, handle_get_todo, handle_list_todos, handle_toggle_todo

pub fn build_router() do
  let router = HTTP.router()
    |> HTTP.on_get("/health", handle_health)
    |> HTTP.on_get("/todos", HTTP.clustered(1, handle_list_todos))
    |> HTTP.on_get("/todos/:id", HTTP.clustered(1, handle_get_todo))
    |> HTTP.on_post("/todos", handle_create_todo)
    |> HTTP.on_put("/todos/:id", handle_toggle_todo)
    |> HTTP.on_delete("/todos/:id", handle_delete_todo)
  router
end
"#;
    write_project_file(&project_dir.join("api/router.mpl"), router_mesh)?;

    let todos_api_mesh = r#"from Runtime.Registry import get_db_path, get_rate_limiter
from Services.RateLimiter import allow_write
from Storage.Todos import create_todo, delete_todo, get_todo, list_todos, toggle_todo
from Types.Todo import Todo

fn todo_to_json(todo :: Todo) -> String do
  Json.encode(todo)
end

fn require_param(request, name :: String) -> String do
  let value = Request.param(request, name)
  case value do
    Some( param) -> param
    None -> ""
  end
end

fn title_from_body(body :: String) -> String do
  String.trim(Json.get(body, "title"))
end

fn not_found_response() do
  HTTP.response(404, json { error : "todo not found" })
end

fn rate_limited_response() do
  HTTP.response(429, json { error : "rate limited" })
end

fn allow_mutation() -> Bool do
  let limiter_pid = get_rate_limiter()
  allow_write(limiter_pid, "todo-write")
end

pub fn handle_list_todos(_request :: Request) -> Response do
  case list_todos(get_db_path()) do
    Ok( todos_json) -> HTTP.response(200, todos_json)
    Err( reason) -> HTTP.response(500, json { error : reason })
  end
end

pub fn handle_get_todo(request :: Request) -> Response do
  let id = require_param(request, "id")
  case get_todo(get_db_path(), id) do
    Ok( todo) -> HTTP.response(200, todo_to_json(todo))
    Err( reason) -> if reason == "todo not found" do
      not_found_response()
    else
      HTTP.response(500, json { error : reason })
    end
  end
end

pub fn handle_create_todo(request) do
  if allow_mutation() do
    let title = title_from_body(Request.body(request))
    if String.length(title) == 0 do
      HTTP.response(400, json { error : "title is required" })
    else
      case create_todo(get_db_path(), title) do
        Ok( todo) -> HTTP.response(201, todo_to_json(todo))
        Err( reason) -> HTTP.response(500, json { error : reason })
      end
    end
  else
    rate_limited_response()
  end
end

pub fn handle_toggle_todo(request) do
  if allow_mutation() do
    let id = require_param(request, "id")
    case toggle_todo(get_db_path(), id) do
      Ok( todo) -> HTTP.response(200, todo_to_json(todo))
      Err( reason) -> if reason == "todo not found" do
        not_found_response()
      else
        HTTP.response(500, json { error : reason })
      end
    end
  else
    rate_limited_response()
  end
end

pub fn handle_delete_todo(request) do
  if allow_mutation() do
    let id = require_param(request, "id")
    case delete_todo(get_db_path(), id) do
      Ok( deleted_id) -> HTTP.response(200, json { status : "deleted", id : deleted_id })
      Err( reason) -> if reason == "todo not found" do
        not_found_response()
      else
        HTTP.response(500, json { error : reason })
      end
    end
  else
    rate_limited_response()
  end
end
"#;
    write_project_file(&project_dir.join("api/todos.mpl"), todos_api_mesh)?;

    let registry_mesh = r#"struct RegistryState do
  db_path :: String
  rate_limiter_pid :: Pid
  window_seconds :: Int
  max_requests :: Int
end

service TodoRegistry do
  fn init(db_path :: String, rate_limiter_pid :: Pid, window_seconds :: Int, max_requests :: Int) -> RegistryState do
    RegistryState {
      db_path : db_path,
      rate_limiter_pid : rate_limiter_pid,
      window_seconds : window_seconds,
      max_requests : max_requests
    }
  end

  call GetDbPath() :: String do|state|
    (state, state.db_path)
  end

  call GetRateLimiter() :: Pid do|state|
    (state, state.rate_limiter_pid)
  end

  call GetWindowSeconds() :: Int do|state|
    (state, state.window_seconds)
  end

  call GetMaxRequests() :: Int do|state|
    (state, state.max_requests)
  end
end

pub fn start_registry(db_path :: String, rate_limiter_pid :: Pid, window_seconds :: Int, max_requests :: Int) do
  let registry_pid = TodoRegistry.start(db_path, rate_limiter_pid, window_seconds, max_requests)
  Process.register("todo_api_registry", registry_pid)
  registry_pid
end

pub fn get_db_path() -> String do
  let registry_pid = Process.whereis("todo_api_registry")
  TodoRegistry.get_db_path(registry_pid)
end

pub fn get_rate_limiter() -> Pid do
  let registry_pid = Process.whereis("todo_api_registry")
  TodoRegistry.get_rate_limiter(registry_pid)
end

pub fn get_window_seconds() -> Int do
  let registry_pid = Process.whereis("todo_api_registry")
  TodoRegistry.get_window_seconds(registry_pid)
end

pub fn get_max_requests() -> Int do
  let registry_pid = Process.whereis("todo_api_registry")
  TodoRegistry.get_max_requests(registry_pid)
end
"#;
    write_project_file(&project_dir.join("runtime/registry.mpl"), registry_mesh)?;

    let rate_limiter_mesh = r#"struct RateLimiterState do
  counts :: Map < String, Int >
  window_seconds :: Int
  max_requests :: Int
end

fn check_limit_impl(state :: RateLimiterState, key :: String) ->( RateLimiterState, Bool) do
  let count = Map.get(state.counts, key)
  let allowed = count < state.max_requests
  let next_counts = if allowed do
    Map.put(state.counts, key, count + 1)
  else
    state.counts
  end
  let next_state = RateLimiterState {
    counts : next_counts,
    window_seconds : state.window_seconds,
    max_requests : state.max_requests
  }
  (next_state, allowed)
end

fn reset_window_impl(state :: RateLimiterState) -> RateLimiterState do
  RateLimiterState {
    counts : Map.new(),
    window_seconds : state.window_seconds,
    max_requests : state.max_requests
  }
end

service TodoWriteRateLimiter do
  fn init(window_seconds :: Int, max_requests :: Int) -> RateLimiterState do
    RateLimiterState {
      counts : Map.new(),
      window_seconds : window_seconds,
      max_requests : max_requests
    }
  end

  call Check(key :: String) :: Bool do|state|
    check_limit_impl(state, key)
  end

  cast Reset() do|state|
    reset_window_impl(state)
  end
end

actor rate_window_ticker(limiter_pid, interval_ms :: Int) do
  Timer.sleep(interval_ms)
  TodoWriteRateLimiter.reset(limiter_pid)
  rate_window_ticker(limiter_pid, interval_ms)
end

pub fn start_rate_limiter(window_seconds :: Int, max_requests :: Int) do
  let limiter_pid = TodoWriteRateLimiter.start(window_seconds, max_requests)
  spawn(rate_window_ticker, limiter_pid, window_seconds * 1000)
  limiter_pid
end

pub fn allow_write(limiter_pid :: Pid, key :: String) -> Bool do
  TodoWriteRateLimiter.check(limiter_pid, key)
end
"#;
    write_project_file(
        &project_dir.join("services/rate_limiter.mpl"),
        rate_limiter_mesh,
    )?;

    let storage_mesh = r#"from Types.Todo import Todo

fn row_to_todo(row) -> Todo do
  Todo {
    id : Map.get(row, "id"),
    title : Map.get(row, "title"),
    completed : Map.get(row, "completed") == "true",
    created_at : Map.get(row, "created_at")
  }
end

fn rows_to_json_loop(rows, index :: Int, total :: Int, acc :: List < String >) -> List < String > do
  if index >= total do
    acc
  else
    let encoded = Json.encode(row_to_todo(List.get(rows, index)))
    rows_to_json_loop(rows, index + 1, total, List.append(acc, encoded))
  end
end

pub fn ensure_schema(db_path :: String) -> Int ! String do
  let db = Sqlite.open(db_path)?
  let applied = Sqlite.execute(
    db,
    "CREATE TABLE IF NOT EXISTS todos (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, completed TEXT NOT NULL, created_at TEXT NOT NULL)",
    []
  )?
  Sqlite.close(db)
  Ok(applied)
end

pub fn list_todos(db_path :: String) -> String ! String do
  let db = Sqlite.open(db_path)?
  let rows = Sqlite.query(db, "SELECT id, title, completed, created_at FROM todos ORDER BY id", [])?
  Sqlite.close(db)
  let encoded = rows_to_json_loop(rows, 0, List.length(rows), List.new())
  Ok("[#{String.join(encoded, ",")}]")
end

pub fn get_todo(db_path :: String, id :: String) -> Todo ! String do
  let db = Sqlite.open(db_path)?
  let rows = Sqlite.query(db, "SELECT id, title, completed, created_at FROM todos WHERE id = ?", [id])?
  Sqlite.close(db)
  if List.length(rows) == 0 do
    Err("todo not found")
  else
    Ok(row_to_todo(List.get(rows, 0)))
  end
end

pub fn create_todo(db_path :: String, title :: String) -> Todo ! String do
  let db = Sqlite.open(db_path)?
  let created_at = DateTime.to_iso8601(DateTime.utc_now())
  let _ = Sqlite.execute(db, "INSERT INTO todos (title, completed, created_at) VALUES (?, ?, ?)", [title, "false", created_at])?
  let rows = Sqlite.query(db, "SELECT id, title, completed, created_at FROM todos WHERE id = last_insert_rowid()", [])?
  Sqlite.close(db)
  if List.length(rows) == 0 do
    Err("todo insert did not return a row")
  else
    Ok(row_to_todo(List.get(rows, 0)))
  end
end

pub fn toggle_todo(db_path :: String, id :: String) -> Todo ! String do
  let current = get_todo(db_path, id)?
  let db = Sqlite.open(db_path)?
  let next_completed = if current.completed do
    "false"
  else
    "true"
  end
  let updated = Sqlite.execute(db, "UPDATE todos SET completed = ? WHERE id = ?", [next_completed, id])?
  let rows = Sqlite.query(db, "SELECT id, title, completed, created_at FROM todos WHERE id = ?", [id])?
  Sqlite.close(db)
  if updated == 0 do
    Err("todo not found")
  else
    if List.length(rows) == 0 do
      Err("todo not found")
    else
      Ok(row_to_todo(List.get(rows, 0)))
    end
  end
end

pub fn delete_todo(db_path :: String, id :: String) -> String ! String do
  let current = get_todo(db_path, id)?
  let db = Sqlite.open(db_path)?
  let deleted = Sqlite.execute(db, "DELETE FROM todos WHERE id = ?", [id])?
  Sqlite.close(db)
  if deleted == 0 do
    Err("todo not found")
  else
    Ok(current.id)
  end
end
"#;
    write_project_file(&project_dir.join("storage/todos.mpl"), storage_mesh)?;

    let todo_type_mesh = r#"pub struct Todo do
  id :: String
  title :: String
  completed :: Bool
  created_at :: String
end deriving(Json)
"#;
    write_project_file(&project_dir.join("types/todo.mpl"), todo_type_mesh)?;

    write_project_file(&project_dir.join("README.md"), &todo_readme(name))?;
    write_project_file(&project_dir.join("Dockerfile"), &todo_dockerfile(name))?;
    write_project_file(
        &project_dir.join(".dockerignore"),
        ".git\n.gitignore\ntarget\n.mesh\n.tmp\n*.sqlite3\n",
    )?;

    println!("Created todo-api project '{}'", name);
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::manifest::Manifest;
    use tempfile::TempDir;

    #[test]
    fn scaffold_creates_directory_structure() {
        let tmp = TempDir::new().unwrap();
        scaffold_project("my-app", tmp.path()).unwrap();

        let project_dir = tmp.path().join("my-app");
        assert!(project_dir.exists(), "Project directory should exist");
        assert!(project_dir.is_dir(), "Project path should be a directory");
        assert!(
            project_dir.join("mesh.toml").exists(),
            "mesh.toml should exist"
        );
        assert!(
            project_dir.join("main.mpl").exists(),
            "main.mpl should exist"
        );
    }

    #[test]
    fn scaffold_mesh_toml_is_valid() {
        let tmp = TempDir::new().unwrap();
        scaffold_project("test-project", tmp.path()).unwrap();

        let toml_path = tmp.path().join("test-project").join("mesh.toml");
        let content = std::fs::read_to_string(&toml_path).unwrap();
        let manifest = Manifest::from_str(&content).unwrap();

        assert_eq!(manifest.package.name, "test-project");
        assert_eq!(manifest.package.version, "0.1.0");
        assert!(manifest.dependencies.is_empty());
        assert!(manifest.cluster.is_none());
    }

    #[test]
    fn scaffold_main_mesh_content() {
        let tmp = TempDir::new().unwrap();
        scaffold_project("hello", tmp.path()).unwrap();

        let main_path = tmp.path().join("hello").join("main.mpl");
        let content = std::fs::read_to_string(&main_path).unwrap();
        assert!(content.contains("fn main()"), "Should have main function");
        assert!(content.contains("IO.puts"), "Should have IO.puts call");
    }

    #[test]
    fn scaffold_clustered_project_writes_public_cluster_contract() {
        let tmp = TempDir::new().unwrap();
        scaffold_clustered_project("clustered", tmp.path()).unwrap();

        let project_dir = tmp.path().join("clustered");
        let manifest_path = project_dir.join("mesh.toml");
        let main_path = project_dir.join("main.mpl");
        let work_path = project_dir.join("work.mpl");
        let readme_path = project_dir.join("README.md");

        assert!(manifest_path.exists(), "clustered mesh.toml should exist");
        assert!(main_path.exists(), "clustered main.mpl should exist");
        assert!(work_path.exists(), "clustered work.mpl should exist");
        assert!(readme_path.exists(), "clustered README.md should exist");

        let manifest = Manifest::from_str(&std::fs::read_to_string(&manifest_path).unwrap())
            .expect("clustered manifest should parse");
        assert!(
            manifest.cluster.is_none(),
            "clustered scaffold should keep mesh.toml package-only"
        );

        let main = std::fs::read_to_string(&main_path).unwrap();
        assert_eq!(main.matches("Node.start_from_env()").count(), 1);
        assert!(main.contains("BootstrapStatus"));
        assert!(main.contains("runtime bootstrap"));
        assert!(main.contains("runtime bootstrap failed"));
        assert!(!main.contains("HTTP.serve("));
        assert!(!main.contains("Continuity.submit_declared_work"));
        assert!(!main.contains("/health"));
        assert!(!main.contains("/work"));
        assert!(!main.contains("Env.get_int"));
        assert!(!main.contains("Node.start("));
        assert!(!main.contains("CLUSTER_PROOF_"));

        let work = std::fs::read_to_string(&work_path).unwrap();
        assert!(work.contains("@cluster pub fn add()"));
        assert!(!work.contains("declared_work_runtime_name"));
        assert!(!work.contains("clustered(work)"));
        assert!(work.contains("1 + 1"));
        assert!(!work.contains("declared_work_target"));
        assert!(!work.contains("Continuity.submit_declared_work"));
        assert!(!work.contains("Continuity.mark_completed"));
        assert!(!work.contains("Timer.sleep"));
        assert!(!work.contains("owner_node"));
        assert!(!work.contains("replica_node"));

        let readme = std::fs::read_to_string(&readme_path).unwrap();
        assert!(readme.contains("mesh.toml` is package-only and intentionally omits `[cluster]`"));
        assert!(readme.contains("Node.start_from_env()"));
        assert!(readme.contains("@cluster pub fn add()"));
        assert!(readme.contains("Work.add"));
        assert!(readme.contains("1 + 1"));
        assert!(readme.contains("MESH_CONTINUITY_ROLE"));
        assert!(readme.contains("MESH_CONTINUITY_PROMOTION_EPOCH"));
        assert!(readme.contains("meshc cluster status"));
        assert!(readme.contains("meshc cluster continuity <node-name@host:port> --json"));
        assert!(
            readme.contains("meshc cluster continuity <node-name@host:port> <request-key> --json")
        );
        assert!(readme.contains("meshc cluster diagnostics"));
        assert!(readme.contains("automatically starts the source-declared `@cluster` function"));
        assert!(!readme.contains("declared_work_runtime_name()"));
        assert!(!readme.contains("clustered(work)"));
        assert!(!readme.contains("Continuity.submit_declared_work"));
        assert!(!readme.contains("HTTP.serve("));
        assert!(!readme.contains("HTTP.clustered("));
        assert!(!readme.contains("/health"));
        assert!(!readme.contains("/work"));
        assert!(!readme.contains("Timer.sleep"));
        assert!(!readme.contains("CLUSTER_PROOF_"));
    }

    #[test]
    fn scaffold_clustered_error_when_directory_exists() {
        let tmp = TempDir::new().unwrap();
        let existing = tmp.path().join("existing-clustered");
        std::fs::create_dir_all(&existing).unwrap();

        let result = scaffold_clustered_project("existing-clustered", tmp.path());
        assert!(result.is_err());
        let err = result.unwrap_err();
        assert!(
            err.contains("already exists"),
            "Error should mention 'already exists', got: {}",
            err
        );
    }

    #[test]
    fn m049_s01_todo_api_database_selector_keeps_sqlite_contract() {
        let tmp = TempDir::new().unwrap();
        scaffold_todo_api_project_with_db("todo-api", tmp.path(), TodoApiDatabase::Sqlite)
            .expect("sqlite todo-api scaffold should succeed");

        let project_dir = tmp.path().join("todo-api");
        assert!(project_dir.join("mesh.toml").exists());
        assert!(project_dir.join("main.mpl").exists());
        assert!(project_dir.join("storage/todos.mpl").exists());

        let main = std::fs::read_to_string(project_dir.join("main.mpl")).unwrap();
        assert!(main.contains("TODO_DB_PATH"));
        assert!(main.contains("ensure_schema"));

        let storage = std::fs::read_to_string(project_dir.join("storage/todos.mpl")).unwrap();
        assert!(storage.contains("Sqlite.open"));
        assert!(storage.contains("CREATE TABLE IF NOT EXISTS todos"));
    }

    #[test]
    fn m049_s01_todo_api_database_selector_fails_closed_for_postgres() {
        let tmp = TempDir::new().unwrap();
        let project_dir = tmp.path().join("todo-api");

        let error =
            scaffold_todo_api_project_with_db("todo-api", tmp.path(), TodoApiDatabase::Postgres)
                .expect_err(
                    "postgres todo-api scaffold should fail closed until the starter lands",
                );

        assert!(
            error.contains("--db postgres"),
            "error should mention the postgres flag contract, got: {error}"
        );
        assert!(
            error.contains("not implemented yet"),
            "error should explain the current dedicated-path state, got: {error}"
        );
        assert!(
            !project_dir.exists(),
            "postgres path should fail before creating {}",
            project_dir.display()
        );
    }

    #[test]
    fn m047_s05_scaffold_todo_api_project_writes_clustered_http_template() {
        let tmp = TempDir::new().unwrap();
        scaffold_todo_api_project("todo-api", tmp.path()).unwrap();

        let project_dir = tmp.path().join("todo-api");
        let manifest_path = project_dir.join("mesh.toml");
        let main_path = project_dir.join("main.mpl");
        let work_path = project_dir.join("work.mpl");
        let readme_path = project_dir.join("README.md");
        let dockerfile_path = project_dir.join("Dockerfile");
        let dockerignore_path = project_dir.join(".dockerignore");
        let router_path = project_dir.join("api/router.mpl");
        let todos_api_path = project_dir.join("api/todos.mpl");
        let health_path = project_dir.join("api/health.mpl");
        let registry_path = project_dir.join("runtime/registry.mpl");
        let limiter_path = project_dir.join("services/rate_limiter.mpl");
        let storage_path = project_dir.join("storage/todos.mpl");
        let todo_type_path = project_dir.join("types/todo.mpl");

        for path in [
            &manifest_path,
            &main_path,
            &work_path,
            &readme_path,
            &dockerfile_path,
            &dockerignore_path,
            &router_path,
            &todos_api_path,
            &health_path,
            &registry_path,
            &limiter_path,
            &storage_path,
            &todo_type_path,
        ] {
            assert!(path.exists(), "missing scaffolded file {}", path.display());
        }

        let manifest = Manifest::from_str(&std::fs::read_to_string(&manifest_path).unwrap())
            .expect("todo scaffold manifest should parse");
        assert_eq!(manifest.package.name, "todo-api");
        assert!(manifest.cluster.is_none());

        let main = std::fs::read_to_string(&main_path).unwrap();
        assert!(main.contains("Node.start_from_env()"));
        assert!(main.contains("start_rate_limiter"));
        assert!(main.contains("start_registry"));
        assert!(main.contains("ensure_schema"));
        assert!(main.contains("HTTP.serve(router, port)"));
        assert!(main.contains("TODO_DB_PATH"));
        assert!(main.contains("TODO_RATE_LIMIT_WINDOW_SECONDS"));
        assert!(main.contains("TODO_RATE_LIMIT_MAX_REQUESTS"));
        assert!(!main.contains("HTTP.clustered("));
        assert!(!main.contains("execute_declared_work"));

        let work = std::fs::read_to_string(&work_path).unwrap();
        assert!(work.contains("@cluster pub fn sync_todos()"));
        assert!(!work.contains("execute_declared_work"));
        assert!(!work.contains("request_key"));
        assert!(!work.contains("attempt_id"));

        let router = std::fs::read_to_string(&router_path).unwrap();
        assert!(router.contains("HTTP.on_get(\"/health\", handle_health)"));
        assert!(router.contains("HTTP.on_get(\"/todos\", HTTP.clustered(1, handle_list_todos))"));
        assert!(router.contains("HTTP.on_get(\"/todos/:id\", HTTP.clustered(1, handle_get_todo))"));
        assert!(router.contains("HTTP.on_post(\"/todos\", handle_create_todo)"));
        assert!(router.contains("HTTP.on_put(\"/todos/:id\", handle_toggle_todo)"));
        assert!(router.contains("HTTP.on_delete(\"/todos/:id\", handle_delete_todo)"));
        assert!(!router.contains("HTTP.on_get(\"/health\", HTTP.clustered("));
        assert!(!router.contains("HTTP.on_post(\"/todos\", HTTP.clustered("));
        assert!(!router.contains("HTTP.on_put(\"/todos/:id\", HTTP.clustered("));
        assert!(!router.contains("HTTP.on_delete(\"/todos/:id\", HTTP.clustered("));
        assert!(!router.contains("HTTP.clustered(handle_list_todos)"));
        assert!(!router.contains("HTTP.clustered(handle_get_todo)"));

        let todos_api = std::fs::read_to_string(&todos_api_path).unwrap();
        assert!(todos_api.contains("allow_write("));
        assert!(todos_api.contains("Json.encode(todo)"));
        assert!(todos_api.contains("rate limited"));
        assert!(todos_api.contains("title is required"));
        assert!(todos_api.contains("pub fn handle_list_todos(_request :: Request) -> Response do"));
        assert!(todos_api.contains("pub fn handle_get_todo(request :: Request) -> Response do"));
        assert!(!todos_api.contains("execute_declared_work"));

        let health = std::fs::read_to_string(&health_path).unwrap();
        assert!(health.contains("clustered_handler : \"Work.sync_todos\""));
        assert!(health.contains("rate_limit_window_seconds"));
        assert!(health.contains("rate_limit_max_requests"));

        let registry = std::fs::read_to_string(&registry_path).unwrap();
        assert!(registry.contains("Process.register(\"todo_api_registry\""));
        assert!(registry.contains("call GetRateLimiter() :: Pid"));
        assert!(registry.contains("call GetDbPath() :: String"));

        let limiter = std::fs::read_to_string(&limiter_path).unwrap();
        assert!(limiter.contains("service TodoWriteRateLimiter do"));
        assert!(limiter.contains("spawn(rate_window_ticker"));
        assert!(limiter.contains("call Check(key :: String) :: Bool"));

        let storage = std::fs::read_to_string(&storage_path).unwrap();
        assert!(storage.contains("Sqlite.open"));
        assert!(storage.contains("CREATE TABLE IF NOT EXISTS todos"));
        assert!(storage.contains("last_insert_rowid()"));
        assert!(storage
            .contains("pub fn delete_todo(db_path :: String, id :: String) -> String ! String"));
        assert!(storage.contains("let current = get_todo(db_path, id)?"));
        assert!(storage.contains("DELETE FROM todos WHERE id = ?"));

        let todo_type = std::fs::read_to_string(&todo_type_path).unwrap();
        assert!(todo_type.contains("pub struct Todo do"));
        assert!(todo_type.contains("end deriving(Json)"));

        let readme = std::fs::read_to_string(&readme_path).unwrap();
        assert!(readme.contains("meshc init --template todo-api"));
        assert!(readme.contains("@cluster pub fn sync_todos()"));
        assert!(readme.contains("Work.sync_todos"));
        assert!(readme.contains("GET /health"));
        assert!(readme.contains("GET /todos"));
        assert!(readme.contains("POST /todos"));
        assert!(readme.contains("PUT /todos/:id"));
        assert!(readme.contains("DELETE /todos/:id"));
        assert!(readme.contains("`GET /todos` and `GET /todos/:id` use `HTTP.clustered(1, ...)`"));
        assert!(
            readme.contains("`GET /health` — local runtime + rate-limit configuration snapshot")
        );
        assert!(readme.contains("list todos through `HTTP.clustered(1, ...)`"));
        assert!(readme.contains("fetch one todo through `HTTP.clustered(1, ...)`"));
        assert!(readme.contains("Mutating routes (`POST`, `PUT`, `DELETE`) stay local"));
        assert!(readme.contains("TODO_DB_PATH"));
        assert!(readme.contains("TODO_RATE_LIMIT_WINDOW_SECONDS"));
        assert!(readme.contains("TODO_RATE_LIMIT_MAX_REQUESTS"));
        assert!(readme.contains("meshc cluster status"));
        assert!(readme.contains("docker build -t todo-api ."));
        assert!(readme.contains("packages the binary produced by `meshc build .`"));
        assert!(readme.contains("the Dockerfile copies the already-compiled `./output` binary"));
        assert!(readme.contains(
            "If you're driving Docker from macOS or Windows, emit `./output` from a Linux builder host, CI job, or container first"
        ));
        assert!(!readme.contains("execute_declared_work"));
        assert!(!readme.contains("does **not** pretend `HTTP.clustered(...)` exists yet"));

        let dockerfile = std::fs::read_to_string(&dockerfile_path).unwrap();
        assert!(dockerfile.contains("FROM ubuntu:24.04"));
        assert!(dockerfile.contains("COPY output /usr/local/bin/todo-api"));
        assert!(dockerfile.contains("ENTRYPOINT [\"/usr/local/bin/todo-api\"]"));
        assert!(dockerfile.contains("EXPOSE 8080 4370"));

        let dockerignore = std::fs::read_to_string(&dockerignore_path).unwrap();
        assert!(dockerignore.contains("*.sqlite3"));
        assert!(dockerignore.contains("target"));
    }

    #[test]
    fn m047_s05_scaffold_todo_api_project_rejects_existing_directory() {
        let tmp = TempDir::new().unwrap();
        let existing = tmp.path().join("todo-api");
        std::fs::create_dir_all(&existing).unwrap();

        let result = scaffold_todo_api_project("todo-api", tmp.path());
        assert!(result.is_err());
        let err = result.unwrap_err();
        assert!(
            err.contains("already exists"),
            "Error should mention 'already exists', got: {}",
            err
        );
    }
}
